# A workflow is a configurable automated process made up of one or more jobs.
# You must create a YAML file to define your workflow configuration
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Automatic Deployment Dev
on:
  push:
    branches:
      - prod

jobs:
  build:
    name: Build prod
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: make build
      - run: make push
      - run: make deploy-prod
